export type ProgramItem = {
  time: string;
  title: string;
};

export const schedule: Record<string, ProgramItem[]> = {
  "Segunda-feira": [
    { time: "05:00", title: "Forró de Ouricuri" },
    { time: "07:00", title: "Jornal da Manhã" },
    { time: "08:00", title: "Aperte o Play" },
    { time: "10:00", title: "E aí Doutor?" },
    { time: "11:00", title: "Bota Pegado" },
    { time: "12:00", title: "Jornal do Meio Dia" },
    { time: "13:00", title: "Turma da Voluntários" },
    { time: "14:00", title: "Solte o Som" },
    { time: "15:00", title: "Recebidos" },
    { time: "17:00", title: "Forró de Ouricuri" },
    { time: "18:00", title: "Mundo Inteiro" },
  ],
  "Terça-feira": [
    { time: "05:00", title: "Forró de Ouricuri" },
    { time: "07:00", title: "Jornal da Manhã" },
    { time: "08:00", title: "Aperte o Play" },
    { time: "10:00", title: "E aí Doutor?" },
    { time: "11:00", title: "Bota Pegado" },
    { time: "12:00", title: "Jornal do Meio Dia" },
    { time: "13:00", title: "Turma da Voluntários" },
    { time: "14:00", title: "Solte o Som" },
    { time: "15:00", title: "Recebidos" },
    { time: "17:00", title: "Forró de Ouricuri" },
    { time: "18:00", title: "Mundo Inteiro" },
  ],
  "Quarta-feira": [
    { time: "05:00", title: "Forró de Ouricuri" },
    { time: "07:00", title: "Jornal da Manhã" },
    { time: "08:00", title: "Aperte o Play" },
    { time: "10:00", title: "E aí Doutor?" },
    { time: "11:00", title: "Bota Pegado" },
    { time: "12:00", title: "Jornal do Meio Dia" },
    { time: "13:00", title: "Turma da Voluntários" },
    { time: "14:00", title: "Solte o Som" },
    { time: "15:00", title: "Recebidos" },
    { time: "17:00", title: "Forró de Ouricuri" },
    { time: "18:00", title: "Mundo Inteiro" },
  ],
  "Quinta-feira": [
    { time: "05:00", title: "Forró de Ouricuri" },
    { time: "07:00", title: "Jornal da Manhã" },
    { time: "08:00", title: "Aperte o Play" },
    { time: "10:00", title: "E aí Doutor?" },
    { time: "11:00", title: "Bota Pegado" },
    { time: "12:00", title: "Jornal do Meio Dia" },
    { time: "13:00", title: "Turma da Voluntários" },
    { time: "14:00", title: "Solte o Som" },
    { time: "15:00", title: "Recebidos" },
    { time: "17:00", title: "Forró de Ouricuri" },
    { time: "18:00", title: "Mundo Inteiro" },
  ],
  "Sexta-feira": [
    { time: "05:00", title: "Forró de Ouricuri" },
    { time: "07:00", title: "Jornal da Manhã" },
    { time: "08:00", title: "Aperte o Play" },
    { time: "10:00", title: "E aí Doutor?" },
    { time: "11:00", title: "Bota Pegado" },
    { time: "12:00", title: "Jornal do Meio Dia" },
    { time: "13:00", title: "Turma da Voluntários" },
    { time: "14:00", title: "Solte o Som" },
    { time: "15:00", title: "Recebidos" },
    { time: "17:00", title: "Forró de Ouricuri" },
    { time: "18:00", title: "Mundo Inteiro" },
  ],
  "Sábado": [
    { time: "09:00", title: "Encontro com Padre Paulinho" },
    { time: "10:00", title: "Programa do Bruno" },
    { time: "12:00", title: "Tô Feliz" },
    { time: "15:00", title: "Alegrai-vos" },
    { time: "17:00", title: "Caminhos de Santidade" },
  ],
  "Domingo": [
    { time: "13:00", title: "A Voz do Araripe" },
    { time: "15:00", title: "Alegrai-vos" },
  ],
};

export const dayOrder = [
  "Segunda-feira",
  "Terça-feira",
  "Quarta-feira",
  "Quinta-feira",
  "Sexta-feira",
  "Sábado",
  "Domingo",
];
